

export const login_check = async() => {

    try{
        return true;
    }
    catch(err)
    {
        console.log(err)
    }

}